version: '3'
services: 
    php-apache:
        build:
            context: ../php-apache
        ports: 
            - 80:80
        volumes:
            - ./DocumentRoot:/var/www/html
        links: 
            - 'mariadb'

    mariadb:
        image: mariadb:10.1
        volumes:
            - mariadb:/var/lib/mysql
        environment:
            TZ: "Europe/Dublin"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "rootpwd"
            MYSQL_USER: 'testuser'
            MYSQL_PASSWORD: 'testpassword'
            MYSQL_DATABASE: 'testdb'

volumes: 
    mariadb: